name: Publish Package to npmjs
on:
  release:
    types: [created]
jobs:
  publish:
    name: Publish JS/TS SDK
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        # Sets up .npmrc file to publish to npm
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: https://registry.npmjs.org/
      # - name: Config
      #   run: npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
      - name: Install
        run: yarn install
      - name: Build
        run: yarn build
      - name: Publish
        run: |
          npm publish ./dist --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
